apiVersion: demo.demo.jonlimpw.io/v1
kind: DemoVolume
metadata:
  labels:
    app.kubernetes.io/name: demovolume
    app.kubernetes.io/instance: demovolume-sample
    app.kubernetes.io/part-of: demo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: demo
  name: demovolume-sample
spec:
 # Add fields here
 Name: demo
 Size: 10
